version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    depends_on:
      - db
    image: zavad93/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app/media/
  frontend:
    env_file: .env
    image: zavad93/kittygram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static
  gateway:
    depends_on:
      - backend
      - frontend
    image: zavad93/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/var/html/media/
